introduction = ("5-HT stands as a pivotal neuromodulator within the brain, orchestrating a diverse array of behavors and physiological "
                "processes that include mood regulation {Dayan, 2009 #1401}, memory {Teixeira, 2018 #924}, sleep {Oikonomou, 2019 #347}, feeding {Lee, 2010 #1406}"
                " and decision-making {Homberg, 2012 #1407}. This broad spectrum of influence is remarkably orchestrated by a limited number of 5-HT releasing "
                "neurons located in the raphe nuclei, which extend their projections across the entire brain {Descarries, 2010 #937}. The intricacy of the 5-HT "
                "system is amplified by the extensive repertoire of Htrs, each linked to distinct "
                "G protein-coupled intracellular pathways, resulting in varied and sometimes opposing effects on neuronal excitability {Marin, 2020 #2938}. "
                "These receptors are categorized into 14 types spread across 7 families, presenting a complex landscape of 5-HT signaling. "
                "To better grasp the impact of 5-HT release, it's crucial to accurately map the expression of each receptor "
                "type among neurons and throughout different brain regions. "
                "Historically, techniques such as immunohistochemistry, autoradiography, in situ hybridization, and microarray analysis have been instrumental "
                "in shedding light on these aspects {Vilaró, 2020 #2939; Hawrylycz, 2012 #2940}. These methodologies have provided foundational insights into the brain-wide effects of 5-HT, "
                "contributing significantly to our current understanding {Salvan, 2023 #2941}. However, the introduction of single-cell RNA-seq and MERFISH has revolutionized "
                "our ability to dissect the serotonergic system. Unlike their predecessors, RNA-seq and MERFISH offer an unparalleled resolution and depth of profiling, "
                "allowing for the intricate detailing of each Htr's expression patterns. This advanced level of detail enriches our comprehension of 5-HT's roles, "
                "paving the way for more precise and nuanced interpretations of its influence across the brain's complex neural networks."
                "To elucidate the complexities tied to the distribution of each Htr subtype, we utilized an RNA-seq dataset provided by the Allen Institute {Yao, 2023 #2828}, "
                "incorporating the associated hierarchical clustering of cells at four nested levels. Spatial distribution data was obtained from "
                "a MERFISH dataset provided by Harvard University {Zhang, 2023 #2887}, "
                "offering a unique window into the expression patterns of these receptors. Our analysis reveals new patterns of receptor "
                "expression with an unparalleled level of detail, and for each Htr we compare our results with the exisiting literature. "
                "To facilitate broader exploration of the Htr landscape throughout the brain, "
                "we have developed an online visualization tool. This platform enables the seamless exploration of both the RNA-seq and MERFISH dataset at different levels of "
                "granularity, providing a comprehensive view of the 5-HT receptor distribution. ")


